# Generated by Django 3.0.6 on 2020-05-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0530', '0002_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='static/mariahcarey_emc2.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
